import React, { useState } from 'react';
import { 
  Briefcase, 
  CheckCircle2, 
  Copy, 
  Check, 
  Sparkles, 
  ArrowRight, 
  MapPin, 
  FileCheck, 
  Flame, 
  RefreshCw,
  Download,
  Award,
  FileDown,
  User,
  X
} from 'lucide-react';
import { TranslationResult } from '../types';
import { SAMPLE_INSTITUTIONAL_EXPERIENCES } from '../data/georgiaResources';
import { generateResumePdf } from '../utils/generateResumePdf';

interface CapabilityTranslatorViewProps {
  onTranslate: (text: string) => Promise<TranslationResult | null>;
  currentResult: TranslationResult | null;
  isLoading: boolean;
  onSendToDecisionTree?: () => void;
}

export const CapabilityTranslatorView: React.FC<CapabilityTranslatorViewProps> = ({
  onTranslate,
  currentResult,
  isLoading,
  onSendToDecisionTree
}) => {
  const [inputText, setInputText] = useState('');
  const [copiedSection, setCopiedSection] = useState<string | null>(null);
  const [isPdfModalOpen, setIsPdfModalOpen] = useState(false);
  const [candidateName, setCandidateName] = useState('');
  const [candidatePhone, setCandidatePhone] = useState('');
  const [candidateEmail, setCandidateEmail] = useState('');
  const [candidateLocation, setCandidateLocation] = useState('Atlanta / Macon, GA Corridor');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputText.trim() || isLoading) return;
    await onTranslate(inputText);
  };

  const handleSelectPreset = (presetText: string) => {
    setInputText(presetText);
  };

  const handleCopy = (text: string, sectionKey: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(sectionKey);
    setTimeout(() => setCopiedSection(null), 2200);
  };

  const generateFullMarkdown = (res: TranslationResult) => {
    return `# COMMERCIAL CAPABILITY DOSSIER
**Commercial Alignment:** ${res.commercialTitle}
**Target Corridor Pathway:** ${res.gaPathway}

## CORE COMPETENCIES
### Technical / Hard Skills:
${res.competencies.hardSkills.map((s) => `- ${s}`).join('\n')}

### High-Agency / Execution Skills:
${res.competencies.softSkills.map((s) => `- ${s}`).join('\n')}

## OUTCOME-DRIVEN RESUME ACHIEVEMENTS
${res.resumeBullets.map((b) => `• ${b}`).join('\n')}

---
*Generated by RRR Capability Engine & Reentry Decision System (Georgia/Atlanta/Macon Corridor)*`;
  };

  const downloadTextFile = (res: TranslationResult) => {
    const content = generateFullMarkdown(res);
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `RRR_Commercial_Translation_${res.commercialTitle.replace(/[^a-zA-Z0-9]/g, '_')}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPdf = (res: TranslationResult) => {
    generateResumePdf(res, {
      candidateName: candidateName.trim() || 'Professional Candidate',
      phone: candidatePhone.trim() || undefined,
      email: candidateEmail.trim() || undefined,
      location: candidateLocation.trim() || undefined,
    });
    setIsPdfModalOpen(false);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      {/* Mode Banner */}
      <div className="bg-stone-900/80 border border-stone-800 rounded-xl p-5 shadow-sm">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="px-2 py-0.5 rounded text-xs font-mono font-semibold bg-amber-500/10 text-amber-400 border border-amber-500/30">
                MODE 1
              </span>
              <h2 className="text-lg font-bold text-stone-100">
                Institutional Capability Translator
              </h2>
            </div>
            <p className="text-xs sm:text-sm text-stone-400 max-w-3xl">
              Convert institutional details, kitchen production, facilities maintenance, mechanical overhauls, or clerk duties into industry-standard job titles, 4 hard and soft competencies, 3 high-impact quantified resume bullets, and fast-hiring Georgia corridor pathways.
            </p>
          </div>
          <div className="shrink-0 flex items-center gap-2">
            <span className="text-[11px] font-mono text-stone-400 bg-stone-950 px-2.5 py-1 rounded border border-stone-800">
              Zero Generic Jargon
            </span>
          </div>
        </div>
      </div>

      {/* Preset Experience Selector */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <span className="text-xs font-mono text-stone-400 uppercase tracking-wider">
            Quick-Select Institutional Trade Profiles
          </span>
          <span className="text-[11px] text-stone-500">Click to populate input</span>
        </div>
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2">
          {SAMPLE_INSTITUTIONAL_EXPERIENCES.map((preset, idx) => (
            <button
              key={idx}
              id={`preset-btn-${idx}`}
              type="button"
              onClick={() => handleSelectPreset(preset.text)}
              className="text-left p-2.5 rounded-lg bg-stone-900 hover:bg-stone-850 border border-stone-800 hover:border-amber-500/50 transition-all text-xs group"
            >
              <div className="font-semibold text-stone-200 group-hover:text-amber-300 truncate">
                {preset.title}
              </div>
              <div className="text-[10px] text-stone-500 font-mono mt-0.5">
                {preset.badge}
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Input Form */}
      <form onSubmit={handleSubmit} className="space-y-3">
        <div className="relative">
          <textarea
            id="institutional-experience-input"
            rows={4}
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
            placeholder="Share institutional experience, past facility duties, shop repairs, or trade work (e.g., 'Worked 4 years on the facilities maintenance crew repairing commercial boilers, replacing HVAC filters, operating electrical diagnostics, and managing 12 crew members with strict safety logging...')"
            className="w-full bg-stone-900/90 border border-stone-700/80 rounded-xl p-4 text-stone-100 placeholder-stone-500 text-sm focus:outline-none focus:ring-2 focus:ring-amber-500/50 focus:border-amber-500 font-sans transition-all leading-relaxed"
          />
        </div>

        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="text-xs font-mono text-stone-500">
            {inputText.trim() ? `${inputText.trim().split(/\s+/).length} words entered` : 'Enter institutional duties above or select a preset'}
          </div>

          <div className="flex items-center gap-2">
            {inputText && (
              <button
                type="button"
                onClick={() => setInputText('')}
                className="px-3 py-2 text-xs text-stone-400 hover:text-stone-200 bg-stone-900 border border-stone-800 rounded-lg hover:bg-stone-800 transition-colors"
              >
                Clear
              </button>
            )}
            <button
              id="translate-capability-submit-btn"
              type="submit"
              disabled={!inputText.trim() || isLoading}
              className="inline-flex items-center gap-2 px-5 py-2 rounded-lg bg-amber-500 hover:bg-amber-400 text-stone-950 font-bold text-sm shadow-md transition-all disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isLoading ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" />
                  <span>Translating Capabilities...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 text-stone-950" />
                  <span>Translate to Commercial Standard</span>
                </>
              )}
            </button>
          </div>
        </div>
      </form>

      {/* Results Display */}
      {currentResult && (
        <div className="space-y-6 pt-2">
          {/* Top Actions Bar */}
          <div className="flex flex-wrap items-center justify-between gap-3 bg-stone-900/60 p-3 rounded-lg border border-stone-800">
            <div className="flex items-center gap-2">
              <Award className="w-4 h-4 text-amber-400" />
              <span className="text-xs font-mono font-semibold uppercase tracking-wider text-stone-300">
                Commercial Translation Ready
              </span>
            </div>
            <div className="flex items-center gap-2">
              <button
                id="download-resume-pdf-btn"
                onClick={() => setIsPdfModalOpen(true)}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded bg-amber-500 hover:bg-amber-400 text-xs font-bold text-stone-950 shadow-sm transition-colors"
              >
                <FileDown className="w-3.5 h-3.5" />
                <span>Download Resume (PDF)</span>
              </button>

              <button
                id="copy-full-dossier-btn"
                onClick={() => handleCopy(generateFullMarkdown(currentResult), 'full')}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded bg-stone-800 hover:bg-stone-700 text-xs font-medium text-stone-200 border border-stone-700 transition-colors"
              >
                {copiedSection === 'full' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedSection === 'full' ? 'Dossier Copied' : 'Copy (MD)'}</span>
              </button>

              <button
                id="download-dossier-file-btn"
                onClick={() => downloadTextFile(currentResult)}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded bg-stone-800 hover:bg-stone-700 text-xs font-medium text-stone-200 border border-stone-700 transition-colors"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download .MD</span>
              </button>

              {onSendToDecisionTree && (
                <button
                  id="advance-to-decision-tree-btn"
                  onClick={onSendToDecisionTree}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded bg-amber-500/20 hover:bg-amber-500/30 text-xs font-semibold text-amber-300 border border-amber-500/40 transition-colors"
                >
                  <span>Launch Day 1-3 Decision Tree</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">
            {/* Section 1: Commercial Alignment */}
            <div className="lg:col-span-12 bg-stone-900 border border-amber-500/30 rounded-xl p-5 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-amber-500/5 rounded-full blur-2xl -mr-10 -mt-10 pointer-events-none"></div>
              <div className="flex items-start justify-between gap-4">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="text-[11px] font-mono font-bold tracking-wider uppercase text-amber-400">
                      1. Commercial Alignment
                    </span>
                    <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-stone-800 text-stone-300 border border-stone-700">
                      Industry Standard Title
                    </span>
                  </div>
                  <h3 className="text-xl sm:text-2xl font-extrabold text-stone-100 font-sans tracking-tight">
                    {currentResult.commercialTitle}
                  </h3>
                </div>
                <button
                  onClick={() => handleCopy(currentResult.commercialTitle, 'title')}
                  className="p-2 rounded-lg bg-stone-800 hover:bg-stone-700 text-stone-400 hover:text-stone-200 transition-colors"
                  title="Copy Title"
                >
                  {copiedSection === 'title' ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
                </button>
              </div>
            </div>

            {/* Section 2: Competencies (Hard & Soft) */}
            <div className="lg:col-span-6 bg-stone-900 border border-stone-800 rounded-xl p-5 space-y-4">
              <div className="flex items-center justify-between border-b border-stone-800 pb-2.5">
                <div className="flex items-center gap-2">
                  <Briefcase className="w-4 h-4 text-amber-400" />
                  <span className="text-xs font-mono font-bold tracking-wider uppercase text-stone-300">
                    2. Competencies (4 Hard & 4 Soft Skills)
                  </span>
                </div>
                <button
                  onClick={() => handleCopy(
                    `Hard Skills:\n${currentResult.competencies.hardSkills.map(s => `- ${s}`).join('\n')}\n\nSoft Skills:\n${currentResult.competencies.softSkills.map(s => `- ${s}`).join('\n')}`,
                    'competencies'
                  )}
                  className="text-stone-400 hover:text-stone-200 p-1.5 rounded hover:bg-stone-800 transition-colors"
                  title="Copy Competencies"
                >
                  {copiedSection === 'competencies' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>

              {/* Hard Skills */}
              <div className="space-y-2">
                <div className="text-[11px] font-mono uppercase tracking-wider text-amber-400/90 font-semibold">
                  Technical & Hard Skills
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {currentResult.competencies.hardSkills.map((skill, idx) => (
                    <div
                      key={idx}
                      className="flex items-start gap-2 p-2.5 rounded-lg bg-stone-950/80 border border-stone-800/80 text-xs text-stone-200"
                    >
                      <CheckCircle2 className="w-3.5 h-3.5 text-amber-400 shrink-0 mt-0.5" />
                      <span className="leading-snug">{skill}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Soft Skills */}
              <div className="space-y-2 pt-2 border-t border-stone-800/60">
                <div className="text-[11px] font-mono uppercase tracking-wider text-sky-400 font-semibold">
                  High-Agency Execution Skills
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {currentResult.competencies.softSkills.map((skill, idx) => (
                    <div
                      key={idx}
                      className="flex items-start gap-2 p-2.5 rounded-lg bg-stone-950/80 border border-stone-800/80 text-xs text-stone-200"
                    >
                      <CheckCircle2 className="w-3.5 h-3.5 text-sky-400 shrink-0 mt-0.5" />
                      <span className="leading-snug">{skill}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Section 4: GA Career Pathway */}
            <div className="lg:col-span-6 bg-stone-900 border border-stone-800 rounded-xl p-5 space-y-4">
              <div className="flex items-center justify-between border-b border-stone-800 pb-2.5">
                <div className="flex items-center gap-2">
                  <MapPin className="w-4 h-4 text-emerald-400" />
                  <span className="text-xs font-mono font-bold tracking-wider uppercase text-stone-300">
                    4. Georgia Corridor Career Pathway
                  </span>
                </div>
                <button
                  onClick={() => handleCopy(currentResult.gaPathway, 'pathway')}
                  className="text-stone-400 hover:text-stone-200 p-1.5 rounded hover:bg-stone-800 transition-colors"
                  title="Copy Pathway"
                >
                  {copiedSection === 'pathway' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>

              <div className="p-4 rounded-lg bg-emerald-950/20 border border-emerald-800/40 space-y-2.5">
                <div className="flex items-center gap-2 text-xs font-mono text-emerald-400 font-semibold">
                  <Flame className="w-3.5 h-3.5 text-emerald-400" />
                  <span>Fastest-Hiring Corridor Placement (Atlanta - Macon - Savannah Hub)</span>
                </div>
                <p className="text-sm text-stone-200 leading-relaxed font-sans">
                  {currentResult.gaPathway}
                </p>
                <div className="flex flex-wrap gap-2 pt-2 border-t border-emerald-900/40 text-[11px] font-mono text-stone-400">
                  <span className="px-2 py-0.5 rounded bg-stone-900 border border-stone-700">
                    HOPE Career Grant Eligible
                  </span>
                  <span className="px-2 py-0.5 rounded bg-stone-900 border border-stone-700">
                    TCSG / Union Track
                  </span>
                  <span className="px-2 py-0.5 rounded bg-stone-900 border border-stone-700">
                    W-2 Direct Hire
                  </span>
                </div>
              </div>
            </div>

            {/* Section 3: Resume Bullets */}
            <div className="lg:col-span-12 bg-stone-900 border border-stone-800 rounded-xl p-5 space-y-4">
              <div className="flex items-center justify-between border-b border-stone-800 pb-2.5">
                <div className="flex items-center gap-2">
                  <FileCheck className="w-4 h-4 text-amber-400" />
                  <span className="text-xs font-mono font-bold tracking-wider uppercase text-stone-300">
                    3. High-Impact Action-Driven Resume Bullets (Clear Outcomes)
                  </span>
                </div>
                <button
                  onClick={() => handleCopy(
                    currentResult.resumeBullets.map((b) => `• ${b}`).join('\n\n'),
                    'bullets'
                  )}
                  className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded bg-stone-800 hover:bg-stone-700 text-xs font-mono text-stone-300 transition-colors"
                >
                  {copiedSection === 'bullets' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedSection === 'bullets' ? 'Copied' : 'Copy Bullets'}</span>
                </button>
              </div>

              <div className="space-y-3">
                {currentResult.resumeBullets.map((bullet, idx) => (
                  <div
                    key={idx}
                    className="p-3.5 rounded-lg bg-stone-950/90 border border-stone-800 hover:border-stone-700 transition-colors flex items-start gap-3 group"
                  >
                    <div className="w-6 h-6 rounded bg-amber-500/10 text-amber-400 border border-amber-500/20 font-mono text-xs flex items-center justify-center shrink-0 mt-0.5">
                      {idx + 1}
                    </div>
                    <div className="space-y-1 flex-1">
                      <p className="text-xs sm:text-sm text-stone-100 leading-relaxed font-sans">
                        {bullet}
                      </p>
                    </div>
                    <button
                      onClick={() => handleCopy(bullet, `bullet-${idx}`)}
                      className="opacity-0 group-hover:opacity-100 p-1 rounded hover:bg-stone-800 text-stone-400 hover:text-stone-200 transition-opacity shrink-0"
                      title="Copy single bullet"
                    >
                      {copiedSection === `bullet-${idx}` ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                    </button>
                  </div>
                ))}
              </div>

              {/* Bottom Quick PDF Export Action */}
              <div className="pt-3 border-t border-stone-800/80 flex flex-col sm:flex-row items-center justify-between gap-3">
                <p className="text-xs text-stone-400 font-sans">
                  Ready to apply? Export these accomplishments and trade competencies into an employer-ready PDF format.
                </p>
                <button
                  id="download-resume-pdf-card-btn"
                  onClick={() => setIsPdfModalOpen(true)}
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-amber-500 hover:bg-amber-400 text-stone-950 font-bold text-xs shadow-md transition-colors shrink-0"
                >
                  <FileDown className="w-4 h-4" />
                  <span>Download Resume (PDF)</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* PDF Customization & Download Modal */}
      {isPdfModalOpen && currentResult && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-stone-950/80 backdrop-blur-sm animate-fade-in">
          <div className="bg-stone-900 border border-stone-700 rounded-2xl max-w-lg w-full p-6 shadow-2xl space-y-5 relative">
            <button
              onClick={() => setIsPdfModalOpen(false)}
              className="absolute top-4 right-4 p-1.5 rounded-lg text-stone-400 hover:text-stone-200 hover:bg-stone-800 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="space-y-1">
              <div className="flex items-center gap-2">
                <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-amber-500/15 text-amber-400 border border-amber-500/30">
                  EXPORT CONFIGURATION
                </span>
                <h3 className="text-lg font-bold text-stone-100">
                  Generate Commercial Resume PDF
                </h3>
              </div>
              <p className="text-xs text-stone-400">
                Customize contact headers before generating your high-impact PDF resume formatted for Georgia corridor employers.
              </p>
            </div>

            <div className="space-y-3.5 text-xs">
              <div className="space-y-1">
                <label className="block font-mono text-stone-300">
                  Candidate Full Name
                </label>
                <input
                  id="pdf-candidate-name-input"
                  type="text"
                  value={candidateName}
                  onChange={(e) => setCandidateName(e.target.value)}
                  placeholder="e.g., Marcus Vance (or leave blank for generic header)"
                  className="w-full bg-stone-950 border border-stone-700 rounded-lg px-3 py-2 text-stone-100 placeholder-stone-600 focus:outline-none focus:ring-1 focus:ring-amber-500"
                />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div className="space-y-1">
                  <label className="block font-mono text-stone-300">
                    Phone Number (Optional)
                  </label>
                  <input
                    id="pdf-candidate-phone-input"
                    type="text"
                    value={candidatePhone}
                    onChange={(e) => setCandidatePhone(e.target.value)}
                    placeholder="e.g., (404) 555-0192"
                    className="w-full bg-stone-950 border border-stone-700 rounded-lg px-3 py-2 text-stone-100 placeholder-stone-600 focus:outline-none focus:ring-1 focus:ring-amber-500"
                  />
                </div>

                <div className="space-y-1">
                  <label className="block font-mono text-stone-300">
                    Email Address (Optional)
                  </label>
                  <input
                    id="pdf-candidate-email-input"
                    type="email"
                    value={candidateEmail}
                    onChange={(e) => setCandidateEmail(e.target.value)}
                    placeholder="e.g., candidate@email.com"
                    className="w-full bg-stone-950 border border-stone-700 rounded-lg px-3 py-2 text-stone-100 placeholder-stone-600 focus:outline-none focus:ring-1 focus:ring-amber-500"
                  />
                </div>
              </div>

              <div className="space-y-1">
                <label className="block font-mono text-stone-300">
                  Target Location / Corridor
                </label>
                <input
                  id="pdf-candidate-location-input"
                  type="text"
                  value={candidateLocation}
                  onChange={(e) => setCandidateLocation(e.target.value)}
                  placeholder="e.g., Atlanta / Macon, GA Corridor"
                  className="w-full bg-stone-950 border border-stone-700 rounded-lg px-3 py-2 text-stone-100 placeholder-stone-600 focus:outline-none focus:ring-1 focus:ring-amber-500"
                />
              </div>

              <div className="p-3 rounded-lg bg-stone-950 border border-stone-800 text-[11px] text-stone-400 space-y-1">
                <div className="font-semibold text-stone-300">Included in PDF:</div>
                <div className="flex items-center gap-1.5 text-stone-400">
                  <Check className="w-3.5 h-3.5 text-amber-400" />
                  <span>Target Title: {currentResult.commercialTitle}</span>
                </div>
                <div className="flex items-center gap-1.5 text-stone-400">
                  <Check className="w-3.5 h-3.5 text-amber-400" />
                  <span>4 Technical Hard Skills & 4 High-Agency Execution Skills</span>
                </div>
                <div className="flex items-center gap-1.5 text-stone-400">
                  <Check className="w-3.5 h-3.5 text-amber-400" />
                  <span>3 Quantified Outcome-Driven Resume Bullets</span>
                </div>
                <div className="flex items-center gap-1.5 text-stone-400">
                  <Check className="w-3.5 h-3.5 text-amber-400" />
                  <span>Georgia Corridor Placement & HOPE Career Grant Track</span>
                </div>
              </div>
            </div>

            <div className="flex items-center justify-end gap-2 pt-2 border-t border-stone-800">
              <button
                type="button"
                onClick={() => setIsPdfModalOpen(false)}
                className="px-4 py-2 rounded-lg bg-stone-800 hover:bg-stone-700 text-stone-300 text-xs font-semibold transition-colors"
              >
                Cancel
              </button>
              <button
                id="confirm-generate-pdf-btn"
                type="button"
                onClick={() => handleDownloadPdf(currentResult)}
                className="inline-flex items-center gap-2 px-5 py-2 rounded-lg bg-amber-500 hover:bg-amber-400 text-stone-950 font-bold text-xs shadow-md transition-colors"
              >
                <FileDown className="w-4 h-4" />
                <span>Download Resume (PDF)</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
