import React, { useState } from 'react';
import { 
  Briefcase, 
  CheckCircle2, 
  Copy, 
  Check, 
  Sparkles, 
  ArrowRight, 
  MapPin, 
  FileCheck, 
  Flame, 
  RefreshCw,
  Download,
  Award,
  FileDown,
  FileText,
  Printer,
  Trash2,
  User,
  X
} from 'lucide-react';
import { TranslationResult } from '../types';
import { SAMPLE_INSTITUTIONAL_EXPERIENCES } from '../data/georgiaResources';
import { generateResumePdf } from '../utils/generateResumePdf';
import { generateResumeDocx } from '../utils/generateResumeDocx';
import { printCapabilityTranslator } from '../utils/printCapabilityTranslator';

interface CapabilityTranslatorViewProps {
  onTranslate: (text: string) => Promise<TranslationResult | null>;
  currentResult: TranslationResult | null;
  isLoading: boolean;
  onSendToDecisionTree?: () => void;
  onClearTranslation?: () => void;
}

export const CapabilityTranslatorView: React.FC<CapabilityTranslatorViewProps> = ({
  onTranslate,
  currentResult,
  isLoading,
  onSendToDecisionTree,
  onClearTranslation
}) => {
  const [inputText, setInputText] = useState(currentResult?.rawExperience || '');
  const [selectedPreset, setSelectedPreset] = useState('');
  const [copiedSection, setCopiedSection] = useState<string | null>(null);
  const [isExportModalOpen, setIsExportModalOpen] = useState(false);
  const [exportFormat, setExportFormat] = useState<'pdf' | 'docx' | 'print'>('print');
  const [candidateName, setCandidateName] = useState('');
  const [candidatePhone, setCandidatePhone] = useState('');
  const [candidateEmail, setCandidateEmail] = useState('');
  const [candidateLocation, setCandidateLocation] = useState('Atlanta / Macon, GA Corridor');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputText.trim() || isLoading) return;
    await onTranslate(inputText);
  };

  const handleSelectPreset = (presetText: string) => {
    setInputText(presetText);
  };

  const handleCopy = (text: string, sectionKey: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(sectionKey);
    setTimeout(() => setCopiedSection(null), 2200);
  };

  const handlePrintToPdf = (res?: TranslationResult | null) => {
    const target = res || currentResult;
    if (!target) return;
    printCapabilityTranslator(target, {
      candidateName: candidateName.trim() || undefined,
      phone: candidatePhone.trim() || undefined,
      email: candidateEmail.trim() || undefined,
      location: candidateLocation.trim() || undefined,
    });
  };

  const generateFullMarkdown = (res: TranslationResult) => {
    return `# COMMERCIAL CAPABILITY DOSSIER
**Commercial Alignment:** ${res.commercialTitle}
**Target Corridor Pathway:** ${res.gaPathway}

## CORE COMPETENCIES
### Technical / Hard Skills:
${res.competencies.hardSkills.map((s) => `- ${s}`).join('\n')}

### High-Agency / Execution Skills:
${res.competencies.softSkills.map((s) => `- ${s}`).join('\n')}

## OUTCOME-DRIVEN RESUME ACHIEVEMENTS
${res.resumeBullets.map((b) => `• ${b}`).join('\n')}

---
*Generated by RRR Capability Engine & Reentry Decision System (Georgia/Atlanta/Macon Corridor)*`;
  };

  const downloadTextFile = (res: TranslationResult) => {
    const content = generateFullMarkdown(res);
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `RRR_Commercial_Translation_${res.commercialTitle.replace(/[^a-zA-Z0-9]/g, '_')}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPdf = (res: TranslationResult) => {
    generateResumePdf(res, {
      candidateName: candidateName.trim() || 'Professional Candidate',
      phone: candidatePhone.trim() || undefined,
      email: candidateEmail.trim() || undefined,
      location: candidateLocation.trim() || undefined,
    });
    setIsExportModalOpen(false);
  };

  const handleDownloadDocx = async (res: TranslationResult) => {
    await generateResumeDocx(res, {
      candidateName: candidateName.trim() || 'Professional Candidate',
      phone: candidatePhone.trim() || undefined,
      email: candidateEmail.trim() || undefined,
      location: candidateLocation.trim() || undefined,
    });
    setIsExportModalOpen(false);
  };

  const openExportModal = (format: 'pdf' | 'docx') => {
    setExportFormat(format);
    setIsExportModalOpen(true);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6 w-full overflow-hidden">
      {/* Mode Banner */}
      <div className="bg-stone-900/80 border border-stone-800 rounded-xl p-5 shadow-sm">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="px-2 py-0.5 rounded text-xs font-mono font-semibold bg-amber-500/10 text-amber-400 border border-amber-500/30">
                MODE 1
              </span>
              <h2 className="text-lg font-bold text-stone-100">
                Institutional Capability Translator
              </h2>
            </div>
            <p className="text-xs sm:text-sm text-stone-400 max-w-3xl">
              Convert institutional details, kitchen production, facilities maintenance, mechanical overhauls, or clerk duties into industry-standard job titles, 4 hard and soft competencies, 3 high-impact quantified resume bullets, and fast-hiring Georgia corridor pathways.
            </p>
          </div>
          <div className="shrink-0 flex items-center gap-2">
            <span className="text-[11px] font-mono text-stone-400 bg-stone-950 px-2.5 py-1 rounded border border-stone-800">
              Zero Generic Jargon
            </span>
          </div>
        </div>
      </div>

      {/* Preset Experience Dropdown Menu (Zero Horizontal Scroll) */}
      <div className="bg-stone-900/70 border border-stone-800/90 rounded-xl p-4 space-y-2">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1.5">
          <label htmlFor="translator-preset-select" className="text-xs font-mono text-amber-400 uppercase tracking-wider font-semibold flex items-center gap-1.5">
            <Sparkles className="w-3.5 h-3.5 text-amber-400" />
            <span>Select Sample Institutional Profile:</span>
          </label>
          <span className="text-[11px] text-stone-400">
            Choose from the dropdown menu to auto-populate the form below
          </span>
        </div>
        <select
          id="translator-preset-select"
          value={selectedPreset}
          onChange={(e) => {
            const val = e.target.value;
            setSelectedPreset(val);
            if (val) {
              handleSelectPreset(val);
            }
          }}
          className="w-full bg-stone-950 border border-stone-700/80 rounded-lg p-2.5 text-xs sm:text-sm text-stone-200 focus:outline-none focus:ring-2 focus:ring-amber-500/50 focus:border-amber-500 font-sans cursor-pointer transition-colors"
        >
          <option value="">-- Choose a standard institutional trade profile (Kitchen, Facilities, Heavy Equipment, Logistics...) --</option>
          {SAMPLE_INSTITUTIONAL_EXPERIENCES.map((preset, idx) => (
            <option key={idx} value={preset.text}>
              {preset.title} — [{preset.badge}]
            </option>
          ))}
        </select>
      </div>

      {/* Input Form */}
      <form onSubmit={handleSubmit} className="space-y-3">
        <div className="relative">
          <textarea
            id="institutional-experience-input"
            rows={4}
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
            placeholder="Share institutional experience, past facility duties, shop repairs, or trade work (e.g., 'Worked 4 years on the facilities maintenance crew repairing commercial boilers, replacing HVAC filters, operating electrical diagnostics, and managing 12 crew members with strict safety logging...')"
            className="w-full bg-stone-900/90 border border-stone-700/80 rounded-xl p-4 text-stone-100 placeholder-stone-500 text-sm focus:outline-none focus:ring-2 focus:ring-amber-500/50 focus:border-amber-500 font-sans transition-all leading-relaxed"
          />
        </div>

        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="text-xs font-mono text-stone-500">
            {inputText.trim() ? `${inputText.trim().split(/\s+/).length} words entered` : 'Enter institutional duties above or select from the dropdown'}
          </div>

          <div className="flex flex-wrap items-center gap-2">
            {inputText && (
              <button
                type="button"
                onClick={() => setInputText('')}
                className="px-3 py-2 text-xs text-stone-400 hover:text-stone-200 bg-stone-900 border border-stone-800 rounded-lg hover:bg-stone-800 transition-colors"
              >
                Clear Input
              </button>
            )}
            <button
              id="translate-capability-submit-btn"
              type="submit"
              disabled={!inputText.trim() || isLoading}
              className="inline-flex items-center gap-2 px-5 py-2 rounded-lg bg-amber-500 hover:bg-amber-400 text-stone-950 font-bold text-sm shadow-md transition-all disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isLoading ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" />
                  <span>Translating Capabilities...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 text-stone-950" />
                  <span>Translate to Commercial Standard</span>
                </>
              )}
            </button>
          </div>
        </div>
      </form>

      {/* Results Display */}
      {currentResult && (
        <div className="space-y-6 pt-2">
          {/* Top Actions Bar */}
          <div className="flex flex-wrap items-center justify-between gap-3 bg-stone-900/60 p-3 rounded-lg border border-stone-800">
            <div className="flex items-center gap-2">
              <Award className="w-4 h-4 text-amber-400" />
              <span className="text-xs font-mono font-semibold uppercase tracking-wider text-stone-300">
                Commercial Translation Ready
              </span>
              <span className="hidden sm:inline-flex px-2 py-0.5 rounded text-[10px] font-mono bg-emerald-950 text-emerald-400 border border-emerald-800/60">
                Saved in Local Storage
              </span>
            </div>
            <div className="flex flex-wrap items-center gap-2">
              <button
                id="print-to-pdf-btn"
                onClick={() => handlePrintToPdf(currentResult)}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded bg-amber-500 hover:bg-amber-400 text-xs font-bold text-stone-950 shadow-sm transition-colors"
                title="Print clean black-and-white dossier or Save as PDF via native browser dialog"
              >
                <Printer className="w-3.5 h-3.5" />
                <span>Print to PDF</span>
              </button>

              <button
                id="download-resume-pdf-btn"
                onClick={() => openExportModal('pdf')}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded bg-stone-800 hover:bg-stone-700 text-xs font-medium text-stone-200 border border-stone-700 transition-colors"
                title="Download formatted PDF resume file"
              >
                <FileDown className="w-3.5 h-3.5 text-amber-400" />
                <span>PDF File</span>
              </button>

              <button
                id="download-resume-docx-btn"
                onClick={() => openExportModal('docx')}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded bg-stone-800 hover:bg-stone-700 text-xs font-medium text-stone-200 border border-stone-700 transition-colors"
                title="Download editable Microsoft Word .docx resume"
              >
                <FileText className="w-3.5 h-3.5 text-sky-400" />
                <span>Word (.docx)</span>
              </button>

              <button
                id="copy-full-dossier-btn"
                onClick={() => handleCopy(generateFullMarkdown(currentResult), 'full')}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded bg-stone-800 hover:bg-stone-700 text-xs font-medium text-stone-200 border border-stone-700 transition-colors"
              >
                {copiedSection === 'full' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedSection === 'full' ? 'Copied' : 'Copy (MD)'}</span>
              </button>

              {onClearTranslation && (
                <button
                  id="clear-saved-translation-btn"
                  onClick={onClearTranslation}
                  className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded text-xs text-rose-400 hover:text-rose-300 hover:bg-rose-950/30 border border-rose-900/40 transition-colors"
                  title="Clear saved translation from localStorage"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">Clear Saved</span>
                </button>
              )}

              {onSendToDecisionTree && (
                <button
                  id="advance-to-decision-tree-btn"
                  onClick={onSendToDecisionTree}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded bg-amber-500/20 hover:bg-amber-500/30 text-xs font-semibold text-amber-300 border border-amber-500/40 transition-colors"
                >
                  <span>Launch Day 1-3 Tree</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">
            {/* Section 1: Commercial Alignment */}
            <div className="lg:col-span-12 bg-stone-900 border border-amber-500/30 rounded-xl p-5 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-amber-500/5 rounded-full blur-2xl -mr-10 -mt-10 pointer-events-none"></div>
              <div className="flex items-start justify-between gap-4">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="text-[11px] font-mono font-bold tracking-wider uppercase text-amber-400">
                      1. Commercial Alignment
                    </span>
                    <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-stone-800 text-stone-300 border border-stone-700">
                      Industry Standard Title
                    </span>
                  </div>
                  <h3 className="text-xl sm:text-2xl font-extrabold text-stone-100 font-sans tracking-tight">
                    {currentResult.commercialTitle}
                  </h3>
                </div>
                <button
                  onClick={() => handleCopy(currentResult.commercialTitle, 'title')}
                  className="p-2 rounded-lg bg-stone-800 hover:bg-stone-700 text-stone-400 hover:text-stone-200 transition-colors"
                  title="Copy Title"
                >
                  {copiedSection === 'title' ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
                </button>
              </div>
            </div>

            {/* Section 2: Competencies (Hard & Soft) */}
            <div className="lg:col-span-6 bg-stone-900 border border-stone-800 rounded-xl p-5 space-y-4">
              <div className="flex items-center justify-between border-b border-stone-800 pb-2.5">
                <div className="flex items-center gap-2">
                  <Briefcase className="w-4 h-4 text-amber-400" />
                  <span className="text-xs font-mono font-bold tracking-wider uppercase text-stone-300">
                    2. Competencies (4 Hard & 4 Soft Skills)
                  </span>
                </div>
                <button
                  onClick={() => handleCopy(
                    `Hard Skills:\n${currentResult.competencies.hardSkills.map(s => `- ${s}`).join('\n')}\n\nSoft Skills:\n${currentResult.competencies.softSkills.map(s => `- ${s}`).join('\n')}`,
                    'competencies'
                  )}
                  className="text-stone-400 hover:text-stone-200 p-1.5 rounded hover:bg-stone-800 transition-colors"
                  title="Copy Competencies"
                >
                  {copiedSection === 'competencies' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>

              {/* Hard Skills */}
              <div className="space-y-2">
                <div className="text-[11px] font-mono uppercase tracking-wider text-amber-400/90 font-semibold">
                  Technical & Hard Skills
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {currentResult.competencies.hardSkills.map((skill, idx) => (
                    <div
                      key={idx}
                      className="flex items-start gap-2 p-2.5 rounded-lg bg-stone-950/80 border border-stone-800/80 text-xs text-stone-200"
                    >
                      <CheckCircle2 className="w-3.5 h-3.5 text-amber-400 shrink-0 mt-0.5" />
                      <span className="leading-snug">{skill}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Soft Skills */}
              <div className="space-y-2 pt-2 border-t border-stone-800/60">
                <div className="text-[11px] font-mono uppercase tracking-wider text-sky-400 font-semibold">
                  High-Agency Execution Skills
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {currentResult.competencies.softSkills.map((skill, idx) => (
                    <div
                      key={idx}
                      className="flex items-start gap-2 p-2.5 rounded-lg bg-stone-950/80 border border-stone-800/80 text-xs text-stone-200"
                    >
                      <CheckCircle2 className="w-3.5 h-3.5 text-sky-400 shrink-0 mt-0.5" />
                      <span className="leading-snug">{skill}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Section 4: GA Career Pathway */}
            <div className="lg:col-span-6 bg-stone-900 border border-stone-800 rounded-xl p-5 space-y-4">
              <div className="flex items-center justify-between border-b border-stone-800 pb-2.5">
                <div className="flex items-center gap-2">
                  <MapPin className="w-4 h-4 text-emerald-400" />
                  <span className="text-xs font-mono font-bold tracking-wider uppercase text-stone-300">
                    4. Georgia Corridor Career Pathway
                  </span>
                </div>
                <button
                  onClick={() => handleCopy(currentResult.gaPathway, 'pathway')}
                  className="text-stone-400 hover:text-stone-200 p-1.5 rounded hover:bg-stone-800 transition-colors"
                  title="Copy Pathway"
                >
                  {copiedSection === 'pathway' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>

              <div className="p-4 rounded-lg bg-emerald-950/20 border border-emerald-800/40 space-y-2.5">
                <div className="flex items-center gap-2 text-xs font-mono text-emerald-400 font-semibold">
                  <Flame className="w-3.5 h-3.5 text-emerald-400" />
                  <span>Fastest-Hiring Corridor Placement (Atlanta - Macon - Savannah Hub)</span>
                </div>
                <p className="text-sm text-stone-200 leading-relaxed font-sans">
                  {currentResult.gaPathway}
                </p>
                <div className="flex flex-wrap gap-2 pt-2 border-t border-emerald-900/40 text-[11px] font-mono text-stone-400">
                  <span className="px-2 py-0.5 rounded bg-stone-900 border border-stone-700">
                    HOPE Career Grant Eligible
                  </span>
                  <span className="px-2 py-0.5 rounded bg-stone-900 border border-stone-700">
                    TCSG / Union Track
                  </span>
                  <span className="px-2 py-0.5 rounded bg-stone-900 border border-stone-700">
                    W-2 Direct Hire
                  </span>
                </div>
              </div>
            </div>

            {/* Section 3: Resume Bullets */}
            <div className="lg:col-span-12 bg-stone-900 border border-stone-800 rounded-xl p-5 space-y-4">
              <div className="flex items-center justify-between border-b border-stone-800 pb-2.5">
                <div className="flex items-center gap-2">
                  <FileCheck className="w-4 h-4 text-amber-400" />
                  <span className="text-xs font-mono font-bold tracking-wider uppercase text-stone-300">
                    3. High-Impact Action-Driven Resume Bullets (Clear Outcomes)
                  </span>
                </div>
                <button
                  onClick={() => handleCopy(
                    currentResult.resumeBullets.map((b) => `• ${b}`).join('\n\n'),
                    'bullets'
                  )}
                  className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded bg-stone-800 hover:bg-stone-700 text-xs font-mono text-stone-300 transition-colors"
                >
                  {copiedSection === 'bullets' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedSection === 'bullets' ? 'Copied' : 'Copy Bullets'}</span>
                </button>
              </div>

              <div className="space-y-3">
                {currentResult.resumeBullets.map((bullet, idx) => (
                  <div
                    key={idx}
                    className="p-3.5 rounded-lg bg-stone-950/90 border border-stone-800 hover:border-stone-700 transition-colors flex items-start gap-3 group"
                  >
                    <div className="w-6 h-6 rounded bg-amber-500/10 text-amber-400 border border-amber-500/20 font-mono text-xs flex items-center justify-center shrink-0 mt-0.5">
                      {idx + 1}
                    </div>
                    <div className="space-y-1 flex-1">
                      <p className="text-xs sm:text-sm text-stone-100 leading-relaxed font-sans">
                        {bullet}
                      </p>
                    </div>
                    <button
                      onClick={() => handleCopy(bullet, `bullet-${idx}`)}
                      className="opacity-0 group-hover:opacity-100 p-1 rounded hover:bg-stone-800 text-stone-400 hover:text-stone-200 transition-opacity shrink-0"
                      title="Copy single bullet"
                    >
                      {copiedSection === `bullet-${idx}` ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                    </button>
                  </div>
                ))}
              </div>

              {/* Bottom Quick Resume Export Action */}
              <div className="pt-3 border-t border-stone-800/80 flex flex-col sm:flex-row items-center justify-between gap-3">
                <p className="text-xs text-stone-400 font-sans">
                  Ready to apply? Export these accomplishments and trade competencies into an employer-ready resume.
                </p>
                <div className="flex flex-wrap items-center gap-2">
                  <button
                    id="download-resume-pdf-card-btn"
                    onClick={() => openExportModal('pdf')}
                    className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-lg bg-amber-500 hover:bg-amber-400 text-stone-950 font-bold text-xs shadow-md transition-colors shrink-0"
                  >
                    <FileDown className="w-4 h-4" />
                    <span>Download PDF</span>
                  </button>

                  <button
                    id="download-resume-docx-card-btn"
                    onClick={() => openExportModal('docx')}
                    className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-lg bg-sky-500 hover:bg-sky-400 text-stone-950 font-bold text-xs shadow-md transition-colors shrink-0"
                  >
                    <FileText className="w-4 h-4" />
                    <span>Download Word (.docx)</span>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Resume Customization & Download Modal */}
      {isExportModalOpen && currentResult && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-stone-950/80 backdrop-blur-sm animate-fade-in">
          <div className="bg-stone-900 border border-stone-700 rounded-2xl max-w-lg w-full p-6 shadow-2xl space-y-5 relative">
            <button
              onClick={() => setIsExportModalOpen(false)}
              className="absolute top-4 right-4 p-1.5 rounded-lg text-stone-400 hover:text-stone-200 hover:bg-stone-800 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="space-y-1">
              <div className="flex items-center gap-2">
                <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-amber-500/15 text-amber-400 border border-amber-500/30">
                  EXPORT CONFIGURATION
                </span>
                <h3 className="text-lg font-bold text-stone-100">
                  Generate Commercial Resume
                </h3>
              </div>
              <p className="text-xs text-stone-400">
                Customize contact headers and choose your format (clean PDF or fully editable Microsoft Word .docx) optimized for Georgia corridor employers and Applicant Tracking Systems (ATS).
              </p>
            </div>

            {/* Format Selector Pills */}
            <div className="grid grid-cols-3 gap-2 bg-stone-950 p-1 rounded-lg border border-stone-800">
              <button
                type="button"
                onClick={() => setExportFormat('print')}
                className={`flex items-center justify-center gap-1.5 py-2 px-2 rounded-md text-xs font-semibold transition-all ${
                  exportFormat === 'print'
                    ? 'bg-amber-500 text-stone-950 font-bold shadow-sm'
                    : 'text-stone-400 hover:text-stone-200 hover:bg-stone-900'
                }`}
              >
                <Printer className="w-3.5 h-3.5" />
                <span>Print to PDF</span>
              </button>
              <button
                type="button"
                onClick={() => setExportFormat('pdf')}
                className={`flex items-center justify-center gap-1.5 py-2 px-2 rounded-md text-xs font-semibold transition-all ${
                  exportFormat === 'pdf'
                    ? 'bg-amber-500 text-stone-950 font-bold shadow-sm'
                    : 'text-stone-400 hover:text-stone-200 hover:bg-stone-900'
                }`}
              >
                <FileDown className="w-3.5 h-3.5" />
                <span>PDF File</span>
              </button>
              <button
                type="button"
                onClick={() => setExportFormat('docx')}
                className={`flex items-center justify-center gap-1.5 py-2 px-2 rounded-md text-xs font-semibold transition-all ${
                  exportFormat === 'docx'
                    ? 'bg-sky-500 text-stone-950 font-bold shadow-sm'
                    : 'text-stone-400 hover:text-stone-200 hover:bg-stone-900'
                }`}
              >
                <FileText className="w-3.5 h-3.5" />
                <span>Word (.docx)</span>
              </button>
            </div>

            <div className="space-y-3.5 text-xs">
              <div className="space-y-1">
                <label className="block font-mono text-stone-300">
                  Candidate Full Name
                </label>
                <input
                  id="export-candidate-name-input"
                  type="text"
                  value={candidateName}
                  onChange={(e) => setCandidateName(e.target.value)}
                  placeholder="e.g., Marcus Vance (or leave blank for generic header)"
                  className="w-full bg-stone-950 border border-stone-700 rounded-lg px-3 py-2 text-stone-100 placeholder-stone-600 focus:outline-none focus:ring-1 focus:ring-amber-500"
                />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div className="space-y-1">
                  <label className="block font-mono text-stone-300">
                    Phone Number (Optional)
                  </label>
                  <input
                    id="export-candidate-phone-input"
                    type="text"
                    value={candidatePhone}
                    onChange={(e) => setCandidatePhone(e.target.value)}
                    placeholder="e.g., (404) 555-0192"
                    className="w-full bg-stone-950 border border-stone-700 rounded-lg px-3 py-2 text-stone-100 placeholder-stone-600 focus:outline-none focus:ring-1 focus:ring-amber-500"
                  />
                </div>

                <div className="space-y-1">
                  <label className="block font-mono text-stone-300">
                    Email Address (Optional)
                  </label>
                  <input
                    id="export-candidate-email-input"
                    type="email"
                    value={candidateEmail}
                    onChange={(e) => setCandidateEmail(e.target.value)}
                    placeholder="e.g., candidate@email.com"
                    className="w-full bg-stone-950 border border-stone-700 rounded-lg px-3 py-2 text-stone-100 placeholder-stone-600 focus:outline-none focus:ring-1 focus:ring-amber-500"
                  />
                </div>
              </div>

              <div className="space-y-1">
                <label className="block font-mono text-stone-300">
                  Target Location / Corridor
                </label>
                <input
                  id="export-candidate-location-input"
                  type="text"
                  value={candidateLocation}
                  onChange={(e) => setCandidateLocation(e.target.value)}
                  placeholder="e.g., Atlanta / Macon, GA Corridor"
                  className="w-full bg-stone-950 border border-stone-700 rounded-lg px-3 py-2 text-stone-100 placeholder-stone-600 focus:outline-none focus:ring-1 focus:ring-amber-500"
                />
              </div>

              <div className="p-3 rounded-lg bg-stone-950 border border-stone-800 text-[11px] text-stone-400 space-y-1">
                <div className="font-semibold text-stone-300">
                  Included in {exportFormat === 'docx' ? 'Word (.docx)' : exportFormat === 'print' ? 'Print to PDF' : 'PDF'}:
                </div>
                <div className="flex items-center gap-1.5 text-stone-400">
                  <Check className="w-3.5 h-3.5 text-amber-400" />
                  <span>Target Title: {currentResult.commercialTitle}</span>
                </div>
                <div className="flex items-center gap-1.5 text-stone-400">
                  <Check className="w-3.5 h-3.5 text-amber-400" />
                  <span>4 Technical Hard Skills & 4 High-Agency Execution Skills</span>
                </div>
                <div className="flex items-center gap-1.5 text-stone-400">
                  <Check className="w-3.5 h-3.5 text-amber-400" />
                  <span>3 Quantified Outcome-Driven Resume Bullets</span>
                </div>
                <div className="flex items-center gap-1.5 text-stone-400">
                  <Check className="w-3.5 h-3.5 text-amber-400" />
                  <span>Georgia Corridor Placement & HOPE Career Grant Track</span>
                </div>
                {exportFormat === 'print' && (
                  <div className="flex items-center gap-1.5 text-amber-400 font-medium pt-1 border-t border-stone-900">
                    <Check className="w-3.5 h-3.5 text-amber-400" />
                    <span>Instant clean black-and-white print preview via native browser print dialog</span>
                  </div>
                )}
                {exportFormat === 'docx' && (
                  <div className="flex items-center gap-1.5 text-sky-400 font-medium pt-1 border-t border-stone-900">
                    <Check className="w-3.5 h-3.5 text-sky-400" />
                    <span>Editable in Microsoft Word, Google Docs, LibreOffice & ATS systems</span>
                  </div>
                )}
              </div>
            </div>

            <div className="flex flex-wrap items-center justify-end gap-2 pt-2 border-t border-stone-800">
              <button
                type="button"
                onClick={() => setIsExportModalOpen(false)}
                className="px-4 py-2 rounded-lg bg-stone-800 hover:bg-stone-700 text-stone-300 text-xs font-semibold transition-colors"
              >
                Cancel
              </button>
              
              {exportFormat === 'print' ? (
                <button
                  id="confirm-print-to-pdf-btn"
                  type="button"
                  onClick={() => {
                    setIsExportModalOpen(false);
                    handlePrintToPdf(currentResult);
                  }}
                  className="inline-flex items-center gap-2 px-5 py-2 rounded-lg bg-amber-500 hover:bg-amber-400 text-stone-950 font-bold text-xs shadow-md transition-colors"
                >
                  <Printer className="w-4 h-4" />
                  <span>Trigger Print to PDF</span>
                </button>
              ) : exportFormat === 'pdf' ? (
                <button
                  id="confirm-generate-pdf-btn"
                  type="button"
                  onClick={() => handleDownloadPdf(currentResult)}
                  className="inline-flex items-center gap-2 px-5 py-2 rounded-lg bg-amber-500 hover:bg-amber-400 text-stone-950 font-bold text-xs shadow-md transition-colors"
                >
                  <FileDown className="w-4 h-4" />
                  <span>Download Resume (PDF)</span>
                </button>
              ) : (
                <button
                  id="confirm-generate-docx-btn"
                  type="button"
                  onClick={() => handleDownloadDocx(currentResult)}
                  className="inline-flex items-center gap-2 px-5 py-2 rounded-lg bg-sky-500 hover:bg-sky-400 text-stone-950 font-bold text-xs shadow-md transition-colors"
                >
                  <FileText className="w-4 h-4" />
                  <span>Download Resume (.DOCX)</span>
                </button>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Clean Black & White Professional Layout for Native Browser Print / Print to PDF */}
      {currentResult && (
        <div id="printable-capability-dossier" className="hidden print:block print-dossier-root">
          {/* Document Header */}
          <div className="print-dossier-header">
            <div className="print-dossier-title">
              {candidateName.trim() ? candidateName.trim().toUpperCase() : 'PROFESSIONAL CANDIDATE'}
            </div>
            <div className="print-dossier-subtitle">
              {currentResult.commercialTitle.toUpperCase()}
            </div>
            <div className="print-dossier-meta">
              {[
                candidateLocation.trim() || 'Georgia Logistics & Trade Corridor (Atlanta / Macon)',
                candidatePhone.trim() || 'Direct Phone: Available upon interview',
                candidateEmail.trim() || 'Email: Available upon direct contact'
              ].join('  |  ')}
            </div>
          </div>

          {/* Section: Commercial Capability Summary */}
          <div className="print-section">
            <div className="print-section-heading">
              1. Commercial Capability Summary
            </div>
            <p className="text-xs leading-relaxed text-black mb-3">
              High-discipline, outcome-driven operational specialist aligning rigorous institutional experience and facilities execution into commercial standards. Demonstrates proven capability in high-accountability environments with strict adherence to safety protocols, equipment reliability, team coordination, and rapid problem resolution across the Georgia logistics and infrastructure corridor.
            </p>
          </div>

          {/* Section: Core Competencies (4 Hard & 4 Soft Skills) */}
          <div className="print-section">
            <div className="print-section-heading">
              2. Core Competencies & Transferable Assets
            </div>
            <div className="grid grid-cols-2 gap-3 mb-3">
              <div className="print-competency-box">
                <div className="font-bold text-xs uppercase mb-1 border-b border-black pb-1">
                  Technical & Hard Skills
                </div>
                <ul className="list-disc pl-4 text-xs space-y-1">
                  {currentResult.competencies.hardSkills.map((skill, i) => (
                    <li key={i}>{skill}</li>
                  ))}
                </ul>
              </div>

              <div className="print-competency-box">
                <div className="font-bold text-xs uppercase mb-1 border-b border-black pb-1">
                  High-Agency Execution Skills
                </div>
                <ul className="list-disc pl-4 text-xs space-y-1">
                  {currentResult.competencies.softSkills.map((skill, i) => (
                    <li key={i}>{skill}</li>
                  ))}
                </ul>
              </div>
            </div>
          </div>

          {/* Section: High-Impact Outcome Resume Bullets */}
          <div className="print-section">
            <div className="print-section-heading">
              3. Outcome-Driven Professional Achievements
            </div>
            <div className="space-y-2 mb-3">
              {currentResult.resumeBullets.map((bullet, i) => (
                <div key={i} className="print-bullet-item">
                  <strong>•</strong> {bullet}
                </div>
              ))}
            </div>
          </div>

          {/* Section: Georgia Corridor Pathway & Training Alignment */}
          <div className="print-section">
            <div className="print-section-heading">
              4. Georgia Corridor Career Pathway & Training Alignment
            </div>
            <div className="print-competency-box">
              <p className="text-xs leading-relaxed font-semibold mb-1">
                {currentResult.gaPathway}
              </p>
              <p className="text-[10px] text-stone-700">
                Placement & Training Tracks: Technical College System of Georgia (TCSG) HOPE Career Grant (100% Tuition-Free) | Georgia Registered Apprenticeships | Verified Fair-Chance Employers.
              </p>
            </div>
          </div>

          {/* Print Footer */}
          <div className="mt-4 pt-2 border-t border-black text-[9px] text-stone-600 flex justify-between">
            <span>RRR Capability Engine & Career Architect — Reentry Career Dossier</span>
            <span>Generated: {new Date().toLocaleDateString()} | ATS-Compliant Format</span>
          </div>
        </div>
      )}
    </div>
  );
};
